name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  fetch-cyz2json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download latest cyz2json release
        uses: robinraju/release-downloader@v1.11
        with:
          repository: "ecotaxa/cyz2json"
          latest: true
          fileName: "*"
          out-file-path: "cytosense_to_ecotaxa_pipeline/bin"

  build-package:
    needs: fetch-cyz2json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '>=3.6'
      
      - name: Install build tools
        run: pip install build wheel setuptools

      - name: Download cyz2json
        run: |
          mkdir -p cytosense_to_ecotaxa_pipeline/bin
          # Download binaries to bin directory

      - name: Build package
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: python -m build
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
