name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  fetch-cyz2json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download latest cyz2json release
        uses: robinraju/release-downloader@v1.11
        with:
          repository: "ecotaxa/cyz2json"
          latest: true
          fileName: "*"
          out-file-path: "downloads"
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: cyz2json-binaries
          path: downloads/*

  build-packages:
    needs: fetch-cyz2json
    strategy:
      matrix:
        include:
          - platform: windows
            binary_path: publish/cyz2Json.exe
          - platform: ubuntu
            binary_path: publish/cyz2Json
          - platform: macos
            binary_path: publish/cyz2Json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '>=3.6'
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: cyz2json-binaries
          path: downloads
      - name: Prepare platform binary
        # Run mkdir -p cytosense_to_ecotaxa_pipeline/bin
        # -rw-r--r-- 1 runner docker 35149 Jan  9 05:57 LICENSE
        # -rw-r--r-- 1 runner docker   519 Jan  9 05:57 README.md
        # -rw-r--r-- 1 runner docker   331 Jan  9 05:57 build.sh
        # -rw-r--r-- 1 runner docker   527 Jan  9 05:57 install.sh
        # -rw-r--r-- 1 runner docker    23 Jan  9 05:57 requirements.txt
        # -rw-r--r-- 1 runner docker   717 Jan  9 05:57 setup.py

        # cytosense_to_ecotaxa_pipeline:
        # total 20
        # -rw-r--r-- 1 runner docker     0 Jan  9 05:57 __init__.py
        # drwxr-xr-x 2 runner docker  4096 Jan  9 05:57 bin
        # -rw-r--r-- 1 runner docker 16142 Jan  9 05:57 main.py

        # downloads:
        # total 466416
        # -rw-r--r-- 1 runner docker 122084464 Jan  9 05:57 cyz2json-macos-latest.zip
        # -rw-r--r-- 1 runner docker 124113822 Jan  9 05:57 cyz2json-ubuntu-latest.zip
        # -rw-r--r-- 1 runner docker 231407117 Jan  9 05:57 cyz2json-windows-latest.zip
        run: |
          mkdir -p cytosense_to_ecotaxa_pipeline/bin
          # ls -l *
          unzip -j "downloads/cyz2json-${{ matrix.platform }}-latest" "${{ matrix.binary_path }}" -d cytosense_to_ecotaxa_pipeline/bin/
          # mv cytosense_to_ecotaxa_pipeline/bin/Cyz2Json* cytosense_to_ecotaxa_pipeline/bin/cyz2json
          ls -l *

      - name: Install build tools
        run: pip install build wheel setuptools
      - name: Build package
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          PLATFORM: ${{ matrix.platform }}
        run: python -m build
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*-${{ matrix.platform }}.whl
            dist/*-${{ matrix.platform }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
