name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  fetch-cyz2json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download latest cyz2json release
        uses: robinraju/release-downloader@v1.11
        with:
          repository: "ecotaxa/cyz2json"
          latest: true
          fileName: "*"
          out-file-path: "downloads"
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: cyz2json-binaries
          path: downloads/*

  build-packages:
    needs: fetch-cyz2json
    strategy:
      matrix:
        platform: [ubuntu, macos, windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '>=3.6'
      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: cyz2json-binaries
          path: downloads
      - name: Prepare platform binary
        run: |
          mkdir -p cytosense_to_ecotaxa_pipeline/bin
          cp downloads/cyz2json-${{ matrix.platform }}-latest.zip cytosense_to_ecotaxa_pipeline/bin/
          cd cytosense_to_ecotaxa_pipeline/bin
          unzip cyz2json-${{ matrix.platform }}-latest.zip
      - name: Install build tools
        run: pip install build wheel setuptools
      - name: Build package
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          PLATFORM: ${{ matrix.platform }}
        run: python -m build
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*-${{ matrix.platform }}.whl
            dist/*-${{ matrix.platform }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
